[build]
builder = "NIXPACKS"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[services]]
name = "web"

[services.web]
buildCommand = "npm run build"
startCommand = "npm start"

# Environment variables that Railway should set
[services.web.variables]
NODE_ENV = "production"
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"
PUPPETEER_EXECUTABLE_PATH = "/usr/bin/google-chrome-stable"

# Build configuration
[build.nixpacks]
aptPkgs = ["google-chrome-stable"] 